<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>LicenceCheck.Tests</RootNamespace>
    <AssemblyName>LicenceCheck.Tests</AssemblyName>
    <TestingPlatformCommandLineArguments>--coverlet-file-prefix $(MSBuildProjectName)</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="Verify.XunitV3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\licence-check\licence-check.csproj" />
  </ItemGroup>

</Project>
