<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TestingPlatformCommandLineArguments>--coverlet-file-prefix $(MSBuildProjectName)</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="CsCheck" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="Sarif.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Equiv.Core\Equiv.Core.csproj" />
    <ProjectReference Include="..\Equiv.TestSupport\Equiv.TestSupport.csproj" />
  </ItemGroup>

</Project>
