<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Z3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Equiv.Core\Equiv.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Equiv.Verify.Z3.Tests" />
  </ItemGroup>

</Project>
