using System.Globalization;
using System.Text;

namespace LicenceCheck;

/// <summary>
/// Pure rendering: turns the gate's passed packages into <c>THIRD-PARTY-NOTICES.md</c>. Keeps the
/// three sections of the hand-written file it replaces (ticket M0-010, AC7). Only the redistributed
/// section reproduces full licence text, matching the file it replaces (a build-and-test-only or
/// samples-only dependency is never shipped, so a table citation is enough); a redistributed
/// licence this renderer does not have canonical text for gets a link to its full text instead of a
/// best-effort transcription.
/// </summary>
internal static class ThirdPartyNoticesRenderer
{
    private static readonly Dictionary<string, string> LicenceText = new(StringComparer.Ordinal)
    {
        ["MIT"] = """
            Permission is hereby granted, free of charge, to any person obtaining a copy
            of this software and associated documentation files (the "Software"), to deal
            in the Software without restriction, including without limitation the rights
            to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
            copies of the Software, and to permit persons to whom the Software is
            furnished to do so, subject to the following conditions:

            The above copyright notice and this permission notice shall be included in all
            copies or substantial portions of the Software.

            THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
            AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
            LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
            OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
            SOFTWARE.
            """,
    };

    private static readonly Dictionary<string, string> LicenceUrl = new(StringComparer.Ordinal)
    {
        ["MIT"] = "https://opensource.org/licenses/MIT",
        ["Apache-2.0"] = "https://www.apache.org/licenses/LICENSE-2.0",
        ["BSD-2-Clause"] = "https://opensource.org/licenses/BSD-2-Clause",
        ["BSD-3-Clause"] = "https://opensource.org/licenses/BSD-3-Clause",
        ["MS-PL"] = "https://opensource.org/licenses/MS-PL",
        ["ISC"] = "https://opensource.org/licenses/ISC",
    };

    public static string Render(IReadOnlyList<ResolvedPackage> passed)
    {
        List<ResolvedPackage> redistributed = Sorted(passed, PackageRole.Redistributed);
        List<ResolvedPackage> buildAndTestOnly = Sorted(passed, PackageRole.BuildAndTestOnly);
        List<ResolvedPackage> samplesOnly = Sorted(passed, PackageRole.SamplesOnly);

        StringBuilder builder = new();
        builder.AppendLine("# Third-party notices");
        builder.AppendLine();
        builder.AppendLine("`equiv` incorporates software from the projects below. This file is generated by");
        builder.AppendLine("`tools/licence-check` from the restored packages' own licence metadata (ticket M0-010); do not");
        builder.AppendLine("hand-edit it. It does not change the terms of `equiv` itself, which is licensed under the");
        builder.AppendLine("Business Source License 1.1 — see [LICENSE](LICENSE). The allowlist and exceptions that keep");
        builder.AppendLine("every dependency clear are recorded in [ADR 0017](docs/adr/0017-licensing-and-ip.md) and");
        builder.AppendLine("`tools/licence-check/policy.json`.");
        builder.AppendLine();

        AppendSection(
            builder,
            "## Redistributed with the product",
            "These packages are linked into the `equiv` binaries and container image, so their notices travel with every release artifact.",
            redistributed,
            includeLicenceText: true);
        AppendSection(
            builder,
            "## Not redistributed — build and test only",
            "These are development dependencies (tests, analyzers, local tools). They are never linked into a shipped artifact.",
            buildAndTestOnly,
            includeLicenceText: false);
        AppendSection(
            builder,
            "## Samples only — not redistributed",
            "`samples/` contains paired .NET Framework 4.8 / .NET 10 fixture solutions, isolated from the root build by `samples/Directory.Build.props`.",
            samplesOnly,
            includeLicenceText: false);

        return builder.ToString();
    }

    private static List<ResolvedPackage> Sorted(IReadOnlyList<ResolvedPackage> passed, PackageRole role) =>
        [.. passed.Where(package => package.Role == role).OrderBy(package => package.Id, StringComparer.Ordinal)];

    private static void AppendSection(StringBuilder builder, string heading, string intro, List<ResolvedPackage> packages, bool includeLicenceText)
    {
        builder.AppendLine(heading);
        builder.AppendLine();
        builder.AppendLine(intro);
        builder.AppendLine();

        if (packages.Count == 0)
        {
            builder.AppendLine("_(none)_");
            builder.AppendLine();
            return;
        }

        builder.AppendLine("| Component | Version | Licence |");
        builder.AppendLine("|---|---|---|");
        foreach (ResolvedPackage package in packages)
        {
            builder.AppendLine(CultureInfo.InvariantCulture, $"| {package.Id} | {package.Version} | {package.DeclaredLicence} |");
        }

        builder.AppendLine();

        if (!includeLicenceText)
        {
            return;
        }

        foreach (string licence in packages.Select(package => package.DeclaredLicence).Distinct(StringComparer.Ordinal).OrderBy(licence => licence, StringComparer.Ordinal))
        {
            builder.AppendLine(CultureInfo.InvariantCulture, $"### {licence} License");
            builder.AppendLine();
            if (LicenceText.TryGetValue(licence, out string? text))
            {
                builder.AppendLine("```");
                builder.AppendLine(text);
                builder.AppendLine("```");
            }
            else if (LicenceUrl.TryGetValue(licence, out string? url))
            {
                builder.AppendLine(CultureInfo.InvariantCulture, $"Full text: <{url}>");
            }
            else
            {
                builder.AppendLine(CultureInfo.InvariantCulture, $"Full text: see the component's own repository (licence \"{licence}\").");
            }

            builder.AppendLine();
        }
    }
}
