<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Equiv.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Sarif.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="RuntimeChanges/runtime-changes.json" />
    <EmbeddedResource Include="ApiEquivalences/api-equivalences.json" />
  </ItemGroup>

</Project>
