<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>CheckCoverage</RootNamespace>
    <AssemblyName>CheckCoverage</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CheckCoverage.Tests" />
  </ItemGroup>

</Project>
